version: '3.3'

services:

  atcoder:
    build:
      context: .
      dockerfile: docker/atcoder/Dockerfile
    container_name: atcoder
    stdin_open: true
    tty: true
    working_dir: '/app'
    volumes:
      - ./:/app
